### ISSUE TITLE
Instalation Error

### ISSUE THREAD

**Issue by lordborok** [wikid24/ffxiv_mmd_tools_helper#1]
When i install the addon and enable it. I get this error:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender_3.4.1.0_x64__ppwjx1n5r4v9t\Blender\3.4\scripts\modules\addon_utils.py", line 369, in enable
    mod.register()
  File "C:\Users\bill\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\ffxiv_mmd_tools_helper\__init__.py", line 104, in register
    bpy.utils.register_class(cls)
RuntimeError: Error: Registering operator class: 'HorizontalJointsFindRigidBodiesByIndexPosition', invalid bl_idname 'ffxiv_mmd_tools_helper.horizontal_joints_find_rigids_by_index', is too long, maximum length is 60

I used version 0.834

**Comment by lordborok** [comment]
I can make it work in Blender 3.3 LTS. I will try to compare if it might be a conflicting Addon in my 3.4.1 or if it might be Blender 3.4 in general that is problem.

**Comment by wikid24** [comment]
just seeing this now,

**Comment by wikid24** [comment]
this has been patched, should be fixed in the latest version
