### ISSUE TITLE
Error Encountered with "Lock Position & Rotation"

### ISSUE THREAD

**Issue by Mas0619** [wikid24/ffxiv_mmd_tools_helper#10]
Hello!
I really appreciate you creating this plugin. As someone who is completely new to model creation and a fan of MMD, I'm truly grateful for this tool.

I encountered some issues while trying to export a model to the PMX Format. Following the tutorial, when I clicked on "Lock position & Rotation," I received the following error message:

Python: Traceback (most recent call last):
  File "C:\Users\20230216\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\ffxiv_mmd_tools_helper\bone_tools.py", line 724, in execute
    lock_position_rotation_bones(armature)
  File "C:\Users\20230216\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\ffxiv_mmd_tools_helper\bone_tools.py", line 282, in lock_position_rotation_bones
    FFXIV_BONE_METADATA_DICTIONARY = get_csv_metadata_by_bone_type("disable_rotate", target_columns)
  File "C:\Users\20230216\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\ffxiv_mmd_tools_helper\bone_tools.py", line 153, in get_csv_metadata_by_bone_type
    bone_type_indices = [header.index(target_column) for target_column in bone_types]
  File "C:\Users\20230216\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\ffxiv_mmd_tools_helper\bone_tools.py", line 153, in <listcomp>
    bone_type_indices = [header.index(target_column) for target_column in bone_types]
ValueError: ['mmd_english', 'mmd_japanese', 'mmd_japaneseLR', 'blender_rigify', 'ffxiv'] is not in list

I also tried exporting without selecting this option, but, uh, the legs ended up looking quite wrong.

![QQ图片20240301072504](https://github.com/wikid24/ffxiv_mmd_tools_helper/assets/130338602/cca97e1f-0659-4656-8e70-7535edc5d9ab)

Could you please assist me with this issue? Additionally, I apologize if my English comes across as odd; it's not my first language.

**Comment by wikid24** [comment]
error message has nothing to do with the issue you're encountering. 

real issues is that FFXIV models have two knee bones, while regular MMD models have only one knee bone.

Please check the guide where it says 'Merge double-jointed knee':
https://github.com/wikid24/ffxiv_mmd_tools_helper/wiki/Export-.pmx-files

This will merge the two knee bones into one knee bone
